spring.application.name=example
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/Library
spring.datasource.username=postgres
spring.datasource.password=rules
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.session.store-type=jdbc
spring.session.initialize-schema=always
server.servlet.session.timeout=5m
spring.sql.init.platform=postgres
sqlconnection.enabled=true
